name: CICD

on:
  push:
    branches: ["cicd-test"]

concurrency:
  group: cicd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Push (CPU)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions: { contents: read, packages: write }

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push (CPU, no cache)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/mishanya-ml:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/mishanya-ml:${{ github.sha }}

      # Sanity-check: убеждаемся, что в образе нет nvidia/*
      - name: Sanity check image (no CUDA stuff)
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mishanya-ml:${{ github.sha }}
          docker run --rm ${{ secrets.DOCKER_HUB_USERNAME }}/mishanya-ml:${{ github.sha }} \
            bash -lc 'test ! -d /usr/local/lib/python3.11/site-packages/nvidia'
        shell: bash

  deploy:
    name: Deploy to VPS
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: Add VPS host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy over SSH and restart container
        uses: appleboy/ssh-action@v0.1.10
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/mishanya-ml:${{ github.sha }}
          CONTAINER_NAME: mishanya-ml
          APP_PORT: "3000"
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: DOCKERHUB_USER,DOCKERHUB_TOKEN,IMAGE_NAME,CONTAINER_NAME,APP_PORT
          script: |
            set -Eeo pipefail
            echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USER}" --password-stdin

            docker rm -f "${CONTAINER_NAME}" 2>/dev/null || true

            # максимальная чистка перед pull
            docker container prune -f || true
            docker image prune -af || true
            docker builder prune -af || true
            docker volume prune -f || true
            docker images "${DOCKERHUB_USER}/mishanya-ml" -q | xargs -r docker rmi -f || true

            export DOCKER_TMPDIR="$HOME/docker-tmp"; mkdir -p "$DOCKER_TMPDIR"

            echo "Pull fresh image: ${IMAGE_NAME}"
            docker pull "${IMAGE_NAME}"

            mkdir -p ~/mishanya-ml-data

            docker run -d --name "${CONTAINER_NAME}" \
              -p ${APP_PORT}:3000 \
              -v ~/mishanya-ml-data:/app/data \
              --restart unless-stopped \
              "${IMAGE_NAME}"

            docker image prune -af || true
            docker logout || true
          debug: true
